/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package esmaieeli.gisFastLocationOptimization.GUI;

import esmaieeli.gisFastLocationOptimization.GIS3D.LayerDefinition;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Amir72c
 */
public class BaseDataDetails extends javax.swing.JDialog {

    MainFramePanel myParent;
    String data[][];
    String headers[];
    Class[] types;

    /**
     * Creates new form BaseDataDetails
     */
    public BaseDataDetails(java.awt.Window window, MainFramePanel parent, ModalityType modal) {
        super(window, modal);
        initComponents();
        myParent = parent;
        ExcelAdapter excelAdapter = new ExcelAdapter(jTable1);

    }

    public void refreshTable() {
        if (myParent.allData != null) {
            int numColumns = myParent.allData.all_Layers.size() + 3;//Node ID/Node lat/Node lon
            int numRecords = myParent.allData.all_Nodes.length;
            types = new Class[numColumns];
            data = new String[numRecords][numColumns];
            headers = new String[numColumns];
            headers[0] = "ID";
            headers[1] = "Latitude";
            headers[2] = "Longtitude";
            for (int i = 3; i < numColumns; i++) {
                headers[i] = ((LayerDefinition) myParent.allData.all_Layers.get(i - 3)).layerName;
                types[i] = java.lang.String.class;
            }
            for (int i = 0; i < myParent.allData.all_Nodes.length; i++) {
                data[i][0] = String.valueOf(myParent.allData.all_Nodes[i].id);
                data[i][1] = String.valueOf(myParent.allData.all_Nodes[i].lat);
                data[i][2] = String.valueOf(myParent.allData.all_Nodes[i].lon);
//                    System.out.println("layers: "+myParent.allData.all_Ways[i].myNodes[j].layers.size());
                for (int k = 0; k < myParent.allData.all_Nodes[i].layers.size(); k++) {
//                        System.out.println("counter: "+counter);
//                        System.out.println("data: "+data.length);
                    if (((LayerDefinition) myParent.allData.all_Layers.get(k)).myType.equals("numeric")) {
                        data[i][k + 3] = String.valueOf(((double) myParent.allData.all_Nodes[i].layers.get(k)));
                    } else {
                        data[i][k + 3] = String.valueOf(((short[]) myParent.allData.all_Nodes[i].layers.get(k))[0]);
                    }
                }
            }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(data, headers));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel12.setText("Node list:");

        jLabel11.setText("Way list:");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel1.setText("Details:");

        jButton1.setText("Close");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        jTextArea3.setText("");
        int temp = jList1.getSelectedIndex();

        jTextArea3.append("ID: " + myParent.allData.all_Nodes[temp].id + "\n");
        jTextArea3.append("lat: " + myParent.allData.all_Nodes[temp].lat + "\n");
        jTextArea3.append("lon: " + myParent.allData.all_Nodes[temp].lon + "\n");
        for (int i = 0; i < myParent.allData.all_Nodes[temp].myWays.length; i++) {
            jTextArea3.append("way id: " + myParent.allData.all_Nodes[temp].myWays[i].id + "\n");
            jTextArea3.append("way type: " + myParent.allData.all_Nodes[temp].myWays[i].type + "\n");
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
        jTextArea3.setText("");
        int temp = jList2.getSelectedIndex();

        jTextArea3.append("ID: " + myParent.allData.all_Ways[temp].id + "\n");
        jTextArea3.append("type: " + myParent.allData.all_Ways[temp].type + "\n");
        jTextArea3.append("is one way: " + myParent.allData.all_Ways[temp].isOneWay + "\n");
        for (int i = 0; i < myParent.allData.all_Ways[temp].myNodes.length; i++) {
            jTextArea3.append("node id: " + myParent.allData.all_Ways[temp].myNodes[i].id + "\n");
            jTextArea3.append("node lat: " + myParent.allData.all_Ways[temp].myNodes[i].lat + "\n");
            jTextArea3.append("node lon: " + myParent.allData.all_Ways[temp].myNodes[i].lon + "\n");
        }
    }//GEN-LAST:event_jList2MouseClicked

    public void make_lists() {
        System.out.println("make lists");
        ListModel NodesList = new ListModel() {
            @Override
            public int getSize() {
                return myParent.allData.all_Nodes.length;
            }

            @Override
            public Object getElementAt(int index) {
                return myParent.allData.all_Nodes[index].id;
            }

            @Override
            public void addListDataListener(ListDataListener l) {
            }

            @Override
            public void removeListDataListener(ListDataListener l) {
            }
        };
        jList1.setModel(NodesList);

        ListModel WaysList = new ListModel() {
            @Override
            public int getSize() {
                return myParent.allData.all_Ways.length;
            }

            @Override
            public Object getElementAt(int index) {
                return myParent.allData.all_Ways[index].id;
            }

            @Override
            public void addListDataListener(ListDataListener l) {
            }

            @Override
            public void removeListDataListener(ListDataListener l) {
            }
        };
        jList2.setModel(WaysList);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
